# Snip bundle — the whole app in one image: a single Bun server that serves the API,
# the short-code redirects, and the built Angular web UI (from ./public).
# Generated by scripts/build-bundle.mjs — do not hand-edit.
FROM oven/bun:1-alpine

WORKDIR /app

# The bundle is self-contained (zero runtime deps), so just copy it in.
# .env (PUBLIC_DIR=./public) is included and auto-loaded by Bun at startup.
COPY . .

# Railway and most PaaS inject $PORT at runtime; the server reads Bun.env.PORT.
# 3000 is the local default and what EXPOSE documents. Bun binds 0.0.0.0 by default.
ENV PORT=3000
EXPOSE 3000

# One process: API + /:code redirects + the static web UI.
CMD ["bun", "server.js"]
